### ISSUE TITLE
Leading zeroes before empty netstrings

### ISSUE THREAD

**Issue by Snawoot** [rj79/pynetstring#1]
Hello!

Thank you for your project! It appeared to be very useful.

[Specification of netstring format](http://cr.yp.to/proto/netstrings.txt) is not very clear about leading zeroes. It makes statements and provides few examples without specifying whether leading zeroes rules are limited to these examples or leading zero rule is universal:

> Any string of 8-bit bytes may be encoded as [len]":"[string]",".
   Here [string] is the string and [len] is a nonempty sequence of ASCII
   digits giving the length of [string] in decimal. The ASCII digits are
   <30> for 0, <31> for 1, and so on up through <39> for 9. Extra zeros
   at the front of [len] are prohibited: [len] begins with <30> exactly
   when [string] is empty.
> 
>  For example, the string "hello world!" is encoded as <31 32 3a 68
   65 6c 6c 6f 20 77 6f 72 6c 64 21 2c>, i.e., "12:hello world!,". The
   empty string is encoded as "0:,".

It's hard to say from specification whether netstring `b"000000000:,"` is allowed or not. [Wikipedia article on Netstring](https://en.wikipedia.org/wiki/Netstring) states:

> The length is written without leading zeroes. Empty string is the only netstring that begins with zero. There is exactly one legal netstring encoding for any byte string.

This particular restriction about only one legal netstring representation vouches for prohibiting leading zeroes in all cases. However, I could not find any reliable source which backs this statement.

Current code allows leading zeroes before empty netstring. It allows unrestricted bloat of input buffer with zeroes. I see two approaches to handle this:
* Restrict all `[len]` from having leading zero. Pros: faster, follows idea of unique netstring representation for each bytestring. Cons: rejects inputs generated by ill applications.
* Silently consume leading zeroes when parsing length, saving only meaningful data into input buffer. This will require additional logic on each length parsing step, but it'll work in all cases without potential input buffer bloat. Pros: follows classic [Robustness principle](https://en.wikipedia.org/wiki/Robustness_principle) "be conservative in what you do, be liberal in what you accept from others.". Cons: slower.

What do you think, which approach is correct one?

If you need help with implementing either approach, please indicate and I'll try to make PR with solution.

**Comment by rj79** [comment]
Hi! Thanks for your input and the patches! I was initially skeptic about allowing more than one leading zero. But after giving it some consideration I agree that it is a sensible approach. Will start pulling your changes.
