### ISSUE TITLE
Questionable handling of length with leading plus and/or spaces

### ISSUE THREAD

**Issue by Snawoot** [rj79/pynetstring#7]
```
>>> pynetstring.decode(b'+3:XXX,')
[b'XXX']
>>> pynetstring.decode(b'         +3:XXX,')
[b'XXX']
```

Not sure if we should tolerate this.

**Comment by Snawoot** [comment]
BTW, whole whitespace company matches:
```
>>> pynetstring.decode(b'\n\r\t\v\x0b\x0c +3:XXX,')
[b'XXX']
```

I guess best move in this case is to get rid of `int()` function and scan char by char, validating chars are only digits and reducing them into length in place. Probably I can put together PR with solution.

**Comment by rj79** [comment]
Yep, only valid digits should be 0-9 in the length descriptor. Which should also catch the negative length case.

**Comment by rj79** [comment]
I think I have a reasonable patch. I'll push it to master so you can check. It still uses int() for the conversion, but first makes sure all characters are valid digits.

**Comment by Snawoot** [comment]
Straightforward filtering approach works fine, but creates performance issues on its own. I also did some job to improve length parsing and here is timing results comparison:

```
[omnipotent@holy-see pynetstring]$ git checkout master 
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
[omnipotent@holy-see pynetstring]$ python3 -m timeit -n 1000 -r 100 -s 'import pynetstring' 'pynetstring.decode(b"0:,0:,0:,3:abc,10:0123456789,52:abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ,")'
1000 loops, best of 100: 22.2 usec per loop
[omnipotent@holy-see pynetstring]$ git checkout strict_int_parsing 
Switched to branch 'strict_int_parsing'
Your branch is up to date with 'origin/strict_int_parsing'.
[omnipotent@holy-see pynetstring]$ python3 -m timeit -n 1000 -r 100 -s 'import pynetstring' 'pynetstring.decode(b"0:,0:,0:,3:abc,10:0123456789,52:abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ,")'
1000 loops, best of 100: 15.7 usec per loop
```

Where `origin/master` branch is pair with master branch of your repo. My solution makes entire parsing about 30% faster. I'll propose PR in few minutes.
